## Aula 1: Introdução ao Numpy e Pandas

## Códigos

### Numpy

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

Abaixo começaremos o codigo passado em aula:

In [1]:
import numpy as np

#### Criando listas

In [2]:
lista = [1, 2, 3, 4, 5]
type(lista)

list

In [3]:
# criando listas numpy a partir de listas do python
lista = [1,2,3,4,5]
listaNumpy = np.array(lista)
print(listaNumpy)
type(listaNumpy)

[1 2 3 4 5]


numpy.ndarray

In [4]:
zeros = [0 for i in range(10)]
zeros

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
#Criando array zeros nump
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Criando array 1 
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Multiplicação de Listas vs np.Array

In [7]:
uns = [1 for i in range(10)]

uns * 5

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [8]:
#Criando array de um numero qualquer
cincos =np.ones(10) * 5
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
#Criando array com sequencia
lista10 = np.arange(0,11)
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Criando lista Com saltos
listaD = np.arange(0,20,2)
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [12]:
#Criando array com valores aleatorios
aleatorio = np.random.rand(20)
aleatorio

array([0.46517164, 0.63514258, 0.75343923, 0.54850931, 0.79113293,
       0.94444964, 0.15744692, 0.34748933, 0.16627197, 0.46606716,
       0.78405325, 0.30043148, 0.0581312 , 0.65986177, 0.31794463,
       0.56279233, 0.97944281, 0.53342668, 0.61202895, 0.72852862])

In [13]:
import random

random.random()

0.7015907681659365

In [14]:
# aleatorio inteiro (10 itens de 0 a 100)
lista1 = np.random.randint(0,100,10)
lista1

array([52, 19, 17, 14, 89, 72, 63, 34, 17,  4])

#### Indexação

In [15]:
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
lista10[5]

5

In [17]:
#Partindo array
lista10[2:7]

array([2, 3, 4, 5, 6])

In [18]:
parte = lista10[3:8:2]
parte

array([3, 5, 7])

In [19]:
#Criando array com sequencia
lista40 = np.arange(10,50)
lista40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Operações simples

In [20]:
lista1

array([52, 19, 17, 14, 89, 72, 63, 34, 17,  4])

In [21]:
listaLista1 = list(lista1)
listaLista1

[52, 19, 17, 14, 89, 72, 63, 34, 17, 4]

In [22]:
lista1 * 2

array([104,  38,  34,  28, 178, 144, 126,  68,  34,   8])

In [23]:
listaLista1 * 2

[52, 19, 17, 14, 89, 72, 63, 34, 17, 4, 52, 19, 17, 14, 89, 72, 63, 34, 17, 4]

In [24]:
lista1 + 1

array([53, 20, 18, 15, 90, 73, 64, 35, 18,  5])

In [25]:
lista1 ** 2

array([2704,  361,  289,  196, 7921, 5184, 3969, 1156,  289,   16],
      dtype=int32)

In [26]:
lista1 / 2

array([26. ,  9.5,  8.5,  7. , 44.5, 36. , 31.5, 17. ,  8.5,  2. ])

In [27]:
lista1 = np.array(lista1)

In [28]:
lista1

array([52, 19, 17, 14, 89, 72, 63, 34, 17,  4])

#### Operações com várias listas

In [29]:
listaLista1 
listaLista2 = listaLista1[:8]

In [30]:
listaLista2

[52, 19, 17, 14, 89, 72, 63, 34]

#### Tomar cuidado ao fazer operações com arrays de tamanhos diferentes

In [31]:
list(np.array(listaLista2) + np.array(listaLista1))

ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [32]:
#soma
lista2 = np.random.randint(0,100,10)
lista1 + lista2

array([118, 115,  68,  23, 144, 106,  83, 117,  55,  24])

In [33]:
lista1 = lista2

In [34]:
lista = [1, 2, 3, 4]
tupla = (1, 2, 3, 4)

In [35]:
lista[2] = 112

In [36]:
tupla = (1, 2, 112, 4)

In [37]:
print('list', id(lista))
print('tuple', id(tupla))

list 1359952905856
tuple 1359974060896


In [38]:
x = 100000000
lista = list(range(x-1))
lista.append(1)
tupla = tuple(range(x))
print(lista.__sizeof__())
print(tupla.__sizeof__())
print(lista.__sizeof__() - tupla.__sizeof__())

900000088
800000024
100000064


In [39]:
lista1[9] = 0

In [40]:
# divisão
lista3 = lista1 / lista2

<ipython-input-40-a7f4b8f15217>:2: RuntimeWarning: invalid value encountered in true_divide
  lista3 = lista1 / lista2


In [41]:
lista3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan])

In [42]:
lista3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan])

In [43]:
lista3 = [i for i in lista3 if i != np.inf]

In [44]:
lista3

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan]

In [45]:
#divisão mult
lista1 * lista2

array([4356, 9216, 2601,   81, 3025, 1156,  400, 6889, 1444,    0])

#### Métodos

In [46]:
lista1

array([66, 96, 51,  9, 55, 34, 20, 83, 38,  0])

In [47]:
#Funções sobre uma matriz
#maior valor
lista1.max()

96

In [48]:
#local do maior valor
lista1.argmax()

1

In [49]:
#maior valor
lista1.min()

0

In [50]:
#local do menor valor
lista1.argmin()

9

In [51]:
#soma de todos os items
lista1.sum()

452

In [52]:
#media
lista1.mean()

45.2

In [53]:
#desvio padrão
lista1.std()

29.559431658947705

In [54]:
#ordenar a lista
lista1.sort()
lista1

array([ 0,  9, 20, 34, 38, 51, 55, 66, 83, 96])

In [55]:
listax = sorted(lista1)

In [56]:
lista1

array([ 0,  9, 20, 34, 38, 51, 55, 66, 83, 96])

In [57]:
#Trocando o tipo dos dados nas lista
lista1 = lista1.astype(int)
lista1

array([ 0,  9, 20, 34, 38, 51, 55, 66, 83, 96])

#### Matrix

In [58]:
listaD = np.arange(0,20,2)

In [59]:
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
#Criando matriz
matriz = listaD.reshape(5, 2)
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

### Problema1: Criar uma matriz 10x2 onde na primeira coluna estejam os valores da listaD e a segunda coluna seja preenchida com zeros

In [61]:
listaD.reshape(10,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [62]:
np.zeros(10).reshape(10, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### Solução 1 - Usando Pandas

In [63]:
import pandas as pd

In [64]:
listaD.reshape(10,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

**Vamos criar um dataframe com o formato que desejamos e depois converte-lo para numpy array**

In [65]:
df = pd.DataFrame({'A': listaD, 'B':np.zeros(10)})
df

A    B
0   0  0.0
1   2  0.0
2   4  0.0
3   6  0.0
4   8  0.0
5  10  0.0
6  12  0.0
7  14  0.0
8  16  0.0
9  18  0.0

In [66]:
df.to_numpy()

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

#### Solução 2 - Usando hstack

In [67]:
np.hstack((listaD.reshape(10,1), np.zeros(10).reshape(10,1)))

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

#### Solução 2 - Usando vstack e matriz transposta

In [68]:
arr = np.vstack((listaD, np.zeros(10)))
arr

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [69]:
# .T gera a matriz transposta ou seja, linha vira coluna

arr.T

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

In [70]:
#mostra qual é o formato da matriz
print(arr.shape)
print(arr.T.shape)

(2, 10)
(10, 2)


In [71]:
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [72]:
#Criando matriz identidade
mIdentidade = np.eye(5)
mIdentidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [74]:
#indexação matriz
matriz[2:,1:]

array([[10],
       [14],
       [18]])

#### Máscaras

In [75]:
aleatorio

array([0.46517164, 0.63514258, 0.75343923, 0.54850931, 0.79113293,
       0.94444964, 0.15744692, 0.34748933, 0.16627197, 0.46606716,
       0.78405325, 0.30043148, 0.0581312 , 0.65986177, 0.31794463,
       0.56279233, 0.97944281, 0.53342668, 0.61202895, 0.72852862])

In [76]:
#Mascaras
aleatorio > 0.5

array([False,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False, False,  True, False,  True,  True,  True,
        True,  True])

In [77]:
aleatorio[aleatorio > 0.5]

array([0.63514258, 0.75343923, 0.54850931, 0.79113293, 0.94444964,
       0.78405325, 0.65986177, 0.56279233, 0.97944281, 0.53342668,
       0.61202895, 0.72852862])

In [78]:
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
#Numeros pares
pares = lista10 % 2 == 0
pares

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [80]:
#Aplicando a mascara a mastriz
lista10[pares]

array([ 0,  2,  4,  6,  8, 10])

In [81]:
#Aplicando a mascara maior que 2
lista10[lista10>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Pandas

#### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [82]:
import pandas as pd

In [83]:
#utilizando um lista simples
minha_lista = [10,20,30]
serie = pd.Series(minha_lista)
serie

0    10
1    20
2    30
dtype: int64

In [84]:
serie.loc[2]

30

In [85]:
arr = np.array(minha_lista)

In [86]:
arr[1]

20

In [87]:
#Acessando dados como um lista
serie[1]

20

In [88]:
#indexação
serie[:2]

0    10
1    20
dtype: int64

In [89]:
#Series com index
labels = ['a','b','c','e']
lista4 = [10,20,30,40]
serieLabel = pd.Series(data=lista4,index=labels)
serieLabel

a    10
b    20
c    30
e    40
dtype: int64

In [90]:
#acessando index 'a' da serie
serieLabel['a']

10

In [91]:
#acessando index 'a' e 'b' da serie
serieLabel['a':'b']

a    10
b    20
dtype: int64

In [92]:
#Series com dicionarios
dicionario = {'a':10,'b':20,'c':30}
pd.Series(dicionario)

a    10
b    20
c    30
dtype: int64

In [93]:
#operações com series
dic1 = {"Brasil":10,"EUA":10,"Japão":10}
serie1 = pd.Series(dic1)
dic2 = {"Brasil":10,"Bolivia":10,"Japão":10}
serie2 = pd.Series(dic2)
serie1 + serie2

Bolivia     NaN
Brasil     20.0
EUA         NaN
Japão      20.0
dtype: float64

In [94]:
#unique
serie1 = pd.Series(['a','b','c','a','d','e','c','a','e','d'])
serie1.unique()

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [95]:
#Contando valores
serie1.value_counts().sort_index()/len(serie1)

a    0.3
b    0.1
c    0.2
d    0.2
e    0.2
dtype: float64

In [96]:
#isin - Para filtar valores
mask = serie1.isin(['b', 'c'])
mask

serie1[mask]

1    b
2    c
6    c
dtype: object

#### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [97]:
np.random.seed(42) #Para o rand ficar igual

lista = np.random.randn(5,3)
lista

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [98]:
index = ['a','b','c','d','e']
colunas = ['x','y','z']
dataFrame = pd.DataFrame(data = lista,index=index,columns=colunas)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [99]:
# acessando coluna 'x', retornando uma serie
dataFrame['x']

a    0.496714
b    1.523030
c    1.579213
d    0.542560
e    0.241962
Name: x, dtype: float64

In [100]:
# acessando colunas 'x' e 'y', retornando um dataframe
dataFrame[['x','y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153
c  1.579213  0.767435
d  0.542560 -0.463418
e  0.241962 -1.913280

In [101]:
#pegando ponto
dataFrame['x']['a']

0.4967141530112327

In [102]:
#Pegando linha
dataFrame.loc['a']

x    0.496714
y   -0.138264
z    0.647689
Name: a, dtype: float64

In [103]:
#Pegando linha por numero
dataFrame.iloc[2]

x    1.579213
y    0.767435
z   -0.469474
Name: c, dtype: float64

In [104]:
#pegando linha e colunuma
dataFrame.loc['a','x']

0.4967141530112327

In [105]:
dataFrame.loc[['a','b'],['x','y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153

In [106]:
#nova coluna 
dataFrame['novo'] = dataFrame['x'] + dataFrame['y']
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [107]:
#remove mas não salva
dataFrame.drop('novo',axis=1)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [108]:
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [109]:
#remove e salva
dataFrame.drop('novo',axis=1,inplace=True)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [110]:
#retirando colunas
dataFrame.drop('e',axis=0)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730

In [111]:
#Seleções através de condições
dataFrame>0

x      y      z
a  True  False   True
b  True  False  False
c  True   True  False
d  True  False  False
e  True  False  False

In [112]:
#utilizando condição como mascara para um novo dataFrame
dataFrame[dataFrame>0]

x         y         z
a  0.496714       NaN  0.647689
b  1.523030       NaN       NaN
c  1.579213  0.767435       NaN
d  0.542560       NaN       NaN
e  0.241962       NaN       NaN

In [113]:
#porem não salva
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [114]:
#retira a linha do y que tem um item menor que 0
dataFrame[dataFrame['y']>0]

x         y         z
c  1.579213  0.767435 -0.469474

In [115]:
#Mesma operação de cima porem so retorna o linha z
dataFrame[dataFrame['y']<0]['z']

a    0.647689
b   -0.234137
d   -0.465730
e   -1.724918
Name: z, dtype: float64

In [116]:
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [117]:
#resetando index
dataFrame.reset_index()

index         x         y         z
0     a  0.496714 -0.138264  0.647689
1     b  1.523030 -0.234153 -0.234137
2     c  1.579213  0.767435 -0.469474
3     d  0.542560 -0.463418 -0.465730
4     e  0.241962 -1.913280 -1.724918

In [118]:
#resetando index sem manter o index antigo
dataFrame.reset_index(drop=True)

x         y         z
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918

In [119]:
dataFrame['nomes'] = ['SP','RJ','BH','SSA','NV']

In [120]:
dataFrame

x         y         z nomes
a  0.496714 -0.138264  0.647689    SP
b  1.523030 -0.234153 -0.234137    RJ
c  1.579213  0.767435 -0.469474    BH
d  0.542560 -0.463418 -0.465730   SSA
e  0.241962 -1.913280 -1.724918    NV

In [121]:
#reordenando as colunas

dataFrame = dataFrame[['x', 'nomes', 'y', 'z']]
dataFrame

x nomes         y         z
a  0.496714    SP -0.138264  0.647689
b  1.523030    RJ -0.234153 -0.234137
c  1.579213    BH  0.767435 -0.469474
d  0.542560   SSA -0.463418 -0.465730
e  0.241962    NV -1.913280 -1.724918

In [122]:
#Alterando o nome das colunas
dataFrame.columns = ['x', 'estados', 'y', 'z']
dataFrame

x estados         y         z
a  0.496714      SP -0.138264  0.647689
b  1.523030      RJ -0.234153 -0.234137
c  1.579213      BH  0.767435 -0.469474
d  0.542560     SSA -0.463418 -0.465730
e  0.241962      NV -1.913280 -1.724918

In [123]:
#criando novo index
dataFrame.set_index('estados',inplace=True)

dataFrame

x         y         z
estados                              
SP       0.496714 -0.138264  0.647689
RJ       1.523030 -0.234153 -0.234137
BH       1.579213  0.767435 -0.469474
SSA      0.542560 -0.463418 -0.465730
NV       0.241962 -1.913280 -1.724918

## Paramos aqui!!!

**indices multiplos**

In [ ]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

In [ ]:
matriz = np.random.randn(6,2)
matriz

In [ ]:
df = pd.DataFrame(matriz,index=hier_index,columns=['A','B'])

df

In [ ]:
df.loc['G1']

In [ ]:
df.xs('G1')

##### Concats e merges

In [ ]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['w','x','y'])
df2 = pd.DataFrame({'B':[1,2,3],'C':[4,5,6],'D':[7,8,9]},index=['x','y','z'])

In [ ]:
df1

In [ ]:
df2

In [ ]:
pd.concat([df1,df2])

In [ ]:
pd.concat([df1,df2],join='inner')

In [ ]:
pd.concat([df1,df2],axis=1)

In [ ]:
pd.concat([df1, df2], axis=1, join='inner')

In [ ]:
df3 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor2":[3,4,5]})
df4 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor3':[1,2,3],"Valor4":[3,4,5]})

df3 

In [ ]:
df4

In [ ]:
pd.merge(df3, df4, on='Paises')

#### Importando dados

In [ ]:
df_imoveis_rj = pd.read_csv('../../00_Datasets/20_Housing/imoveis_Rio_de_Janeiro.csv')
df_imoveis_rj.head()

In [ ]:
df_imoveis_rj = pd.read_csv('../../00_Datasets/20_Housing/imoveis_Rio_de_Janeiro.csv', sep=';')
df_imoveis_rj.head()

##### Nan Values

In [ ]:
#Drop nan
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

In [ ]:
df.dropna(subset=['col2'])

In [ ]:
df.dropna()

In [ ]:
df.fillna('Preencher')

#### Titanic

In [ ]:
df_titanic = pd.read_csv('../datasets/titanic.csv')

In [ ]:
df_titanic.head()

In [ ]:
df_titanic['Age'].mean()

In [ ]:
df_titanic['Age'].mean()

In [ ]:
df_titanic['Age'].std()

In [ ]:
df_titanic['Age'].mode()

In [ ]:
df_titanic['Age'].max()

In [ ]:
df_titanic['Age'].min()

In [ ]:
df_titanic['Age'].value_counts()

In [ ]:
df_titanic['Age'].describe()

In [ ]:
df_titanic.groupby('Embarked')['Survived'].agg(casos='count',
                                               media='mean')

In [ ]:
df_titanic.isnull().sum()

In [ ]:
df_titanic['Embarked'].value_counts()

In [ ]:
df_titanic['Embarked'].mode()[0]

In [ ]:
df_titanic['Embarked'].fillna(df_titanic['Embarked'].mode()[0]).value_counts()

In [ ]:
df_titanic.head()

In [ ]:
df_titanic.columns

In [ ]:
drop_col = ['PassengerId', 'Name']
df_titanic.drop(drop_col, axis=1).duplicated()

In [ ]:
mask = df_titanic.drop(drop_col, axis=1).duplicated()

In [ ]:
df_titanic.loc[mask, ].head()