## Aula 1: Introdução ao Numpy e Pandas

## Códigos

### Numpy

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

Abaixo começaremos o codigo passado em aula:

In [1]:
import numpy as np

#### Criando listas

In [2]:
lista = [1, 2, 3, 4, 5]
type(lista)

list

In [3]:
# criando listas numpy a partir de listas do python
lista = [1,2,3,4,5]
listaNumpy = np.array(lista)
print(listaNumpy)
type(listaNumpy)

[1 2 3 4 5]


numpy.ndarray

In [4]:
zeros = [0 for i in range(10)]
zeros

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
#Criando array zeros nump
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Criando array 1 
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Multiplicação de Listas vs np.Array

In [7]:
uns = [1 for i in range(10)]

uns * 5

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [8]:
#Criando array de um numero qualquer
cincos = np.ones(10) * 5
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
#Criando array com sequencia
lista10 = np.arange(0,11)
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Criando lista Com saltos
listaD = np.arange(0,20,2)
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [16]:
#Criando array com valores aleatorios
aleatorio = np.random.rand(20)
aleatorio

array([0.4240144 , 0.64562906, 0.51975873, 0.74267686, 0.47738262,
       0.21470495, 0.15470351, 0.45080454, 0.67414623, 0.83333996,
       0.26001088, 0.08200161, 0.98842148, 0.99381165, 0.98743732,
       0.63790136, 0.42955014, 0.41394902, 0.56229692, 0.01424981])

In [17]:
import random

random.random()

0.9034926466507626

In [18]:
# aleatorio inteiro (10 itens de 0 a 100)
lista1 = np.random.randint(0,100,10)
lista1

array([95, 87, 88,  3, 97, 24, 14, 37, 61, 53])

#### Indexação

In [19]:
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
lista10[5]

5

In [23]:
#Partindo array
lista10[2:7]

array([2, 3, 4, 5, 6])

In [24]:
parte = lista10[3:8:2]
parte

array([3, 5, 7])

In [25]:
#Criando array com sequencia
lista40 = np.arange(10,50)
lista40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Operações simples

In [26]:
lista1

array([95, 87, 88,  3, 97, 24, 14, 37, 61, 53])

In [27]:
listaLista1 = list(lista1)
listaLista1

[95, 87, 88, 3, 97, 24, 14, 37, 61, 53]

In [31]:
lista1 * 2

array([190, 174, 176,   6, 194,  48,  28,  74, 122, 106])

In [32]:
listaLista1 * 2

[95, 87, 88, 3, 97, 24, 14, 37, 61, 53, 95, 87, 88, 3, 97, 24, 14, 37, 61, 53]

In [33]:
lista1 + 1

array([96, 88, 89,  4, 98, 25, 15, 38, 62, 54])

In [34]:
lista1 ** 2

array([9025, 7569, 7744,    9, 9409,  576,  196, 1369, 3721, 2809],
      dtype=int32)

In [35]:
lista1 / 2

array([47.5, 43.5, 44. ,  1.5, 48.5, 12. ,  7. , 18.5, 30.5, 26.5])

In [27]:
lista1 = np.array(lista1)

In [37]:
lista1

array([95, 87, 88,  3, 97, 24, 14, 37, 61, 53])

#### Operações com várias listas

In [38]:
listaLista1 
listaLista2 = listaLista1[:8]

In [40]:
listaLista1
listaLista2 = listaLista1[:]

In [43]:
listaLista1 + listaLista1

[95, 87, 88, 3, 97, 24, 14, 37, 61, 53, 95, 87, 88, 3, 97, 24, 14, 37, 61, 53]

In [45]:
soma = []
for i in range(len(listaLista1)):
    soma.append(listaLista1[i]+listaLista2[i])

soma
    

[190, 174, 176, 6, 194, 48, 28, 74, 122, 106]

In [48]:
[listaLista1[i]+listaLista2[i] for i in range(len(listaLista1))]

[190, 174, 176, 6, 194, 48, 28, 74, 122, 106]

In [56]:
list(zip(listaLista1, list(np.ones(10))))

[(95, 1.0),
 (87, 1.0),
 (88, 1.0),
 (3, 1.0),
 (97, 1.0),
 (24, 1.0),
 (14, 1.0),
 (37, 1.0),
 (61, 1.0),
 (53, 1.0)]

In [47]:
[]

[l1+l2 for l1, l2 in zip(listaLista1, listaLista2)]
    

[190, 174, 176, 6, 194, 48, 28, 74, 122, 106]

In [46]:
listaLista2

[95, 87, 88, 3, 97, 24, 14, 37, 61, 53]

#### Tomar cuidado ao fazer operações com arrays de tamanhos diferentes

In [61]:
list(np.array(listaLista2) + np.array(listaLista1))

[190, 174, 176, 6, 194, 48, 28, 74, 122, 106]

In [64]:
#soma
lista2 = np.random.randint(0,100,10)
lista1 + lista2

array([118, 137, 101,  77, 157,  98,  86,  70,  96,  60])

In [33]:
lista1 = lista2

In [34]:
lista = [1, 2, 3, 4]
tupla = (1, 2, 3, 4)

In [35]:
lista[2] = 112

In [36]:
tupla = (1, 2, 112, 4)

In [37]:
print('list', id(lista))
print('tuple', id(tupla))

list 1359952905856
tuple 1359974060896


In [38]:
x = 100000000
lista = list(range(x-1))
lista.append(1)
tupla = tuple(range(x))
print(lista.__sizeof__())
print(tupla.__sizeof__())
print(lista.__sizeof__() - tupla.__sizeof__())

900000088
800000024
100000064


In [39]:
lista1[9] = 0

In [65]:
# divisão
lista3 = lista1 / lista2

In [41]:
lista3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan])

In [42]:
lista3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan])

In [43]:
lista3 = [i for i in lista3 if i != np.inf]

In [44]:
lista3

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan]

In [45]:
#divisão mult
lista1 * lista2

array([4356, 9216, 2601,   81, 3025, 1156,  400, 6889, 1444,    0])

#### Métodos

In [66]:
lista1

array([95, 87, 88,  3, 97, 24, 14, 37, 61, 53])

In [67]:
#Funções sobre uma matriz
#maior valor
lista1.max()

97

In [68]:
#local do maior valor
lista1.argmax()

4

In [69]:
#maior valor
lista1.min()

3

In [70]:
#local do menor valor
lista1.argmin()

3

In [71]:
#soma de todos os items
lista1.sum()

559

In [72]:
#media
lista1.mean()

55.9

In [73]:
#desvio padrão
lista1.std()

33.434862045475825

In [74]:
#ordenar a lista
lista1.sort()
lista1

array([ 3, 14, 24, 37, 53, 61, 87, 88, 95, 97])

In [75]:
listax = sorted(lista1)

In [76]:
lista1

array([ 3, 14, 24, 37, 53, 61, 87, 88, 95, 97])

In [78]:
#Trocando o tipo dos dados nas lista
lista1 = lista1.astype(int)
lista1

array([ 3, 14, 24, 37, 53, 61, 87, 88, 95, 97])

#### Matrix

In [79]:
listaD = np.arange(0,20,2)

In [80]:
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
#Criando matriz
matriz = listaD.reshape(5, 2)
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

### Problema1: Criar uma matriz 10x2 onde na primeira coluna estejam os valores da listaD e a segunda coluna seja preenchida com zeros

In [82]:
listaD.reshape(10,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [83]:
np.zeros(10).reshape(10, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### Solução 1 - Usando Pandas

In [85]:
import pandas as pd

In [86]:
listaD.reshape(10,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

**Vamos criar um dataframe com o formato que desejamos e depois converte-lo para numpy array**

In [87]:
df = pd.DataFrame({'A': listaD, 'B':np.zeros(10)})
df

A    B
0   0  0.0
1   2  0.0
2   4  0.0
3   6  0.0
4   8  0.0
5  10  0.0
6  12  0.0
7  14  0.0
8  16  0.0
9  18  0.0

In [88]:
df.to_numpy()

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

#### Solução 2 - Usando hstack

In [89]:
np.hstack((listaD.reshape(10,1), np.zeros(10).reshape(10,1)))

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

#### Solução 2 - Usando vstack e matriz transposta

In [90]:
arr = np.vstack((listaD, np.zeros(10)))
arr

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [91]:
# .T gera a matriz transposta ou seja, linha vira coluna

arr.T

array([[ 0.,  0.],
       [ 2.,  0.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [12.,  0.],
       [14.,  0.],
       [16.,  0.],
       [18.,  0.]])

In [70]:
#mostra qual é o formato da matriz
print(arr.shape)
print(arr.T.shape)

(2, 10)
(10, 2)


In [71]:
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [92]:
#Criando matriz identidade
mIdentidade = np.eye(5)
mIdentidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [93]:
#indexação matriz
matriz[2:,1:]

array([[10],
       [14],
       [18]])

#### Máscaras

In [100]:
aleatorio

array([0.4240144 , 0.64562906, 0.51975873, 0.74267686, 0.47738262,
       0.21470495, 0.15470351, 0.45080454, 0.67414623, 0.83333996,
       0.26001088, 0.08200161, 0.98842148, 0.99381165, 0.98743732,
       0.63790136, 0.42955014, 0.41394902, 0.56229692, 0.01424981])

In [95]:
#Mascaras
aleatorio > 0.5

array([False,  True,  True,  True, False, False, False, False,  True,
        True, False, False,  True,  True,  True,  True, False, False,
        True, False])

In [110]:
aleatorio[~(aleatorio > 0.5)]

array([0.4240144 , 0.47738262, 0.21470495, 0.15470351, 0.45080454,
       0.26001088, 0.08200161, 0.42955014, 0.41394902, 0.01424981])

In [111]:
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
#Numeros pares
pares = lista10 % 2 == 0
pares

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [112]:
#Aplicando a mascara a mastriz
lista10[pares]

array([ 0,  2,  4,  6,  8, 10])

In [113]:
#Aplicando a mascara maior que 2
lista10[lista10>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Pandas

#### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [114]:
import pandas as pd

In [116]:
#utilizando um lista simples
minha_lista = [10,20,30]
serie = pd.Series(minha_lista)
serie

0    10
1    20
2    30
dtype: int64

In [117]:
serie.loc[2]

30

In [122]:
arr = np.array(minha_lista)

In [119]:
arr[1]

20

In [120]:
#Acessando dados como um lista
serie[1]

20

In [121]:
#indexação
serie[:2]

0    10
1    20
dtype: int64

In [123]:
#Series com index
labels = ['a','b','c','e']
lista4 = [10,20,30,40]
serieLabel = pd.Series(data=lista4,index=labels)
serieLabel

a    10
b    20
c    30
e    40
dtype: int64

In [124]:
#acessando index 'a' da serie
serieLabel['a']

10

In [125]:
#acessando index 'a' e 'b' da serie
serieLabel['a':'b']

a    10
b    20
dtype: int64

In [126]:
#Series com dicionarios
dicionario = {'a':10,'b':20,'c':30}
pd.Series(dicionario)

a    10
b    20
c    30
dtype: int64

In [127]:
#operações com series
dic1 = {"Brasil":10,"EUA":10,"Japão":10}
serie1 = pd.Series(dic1)
dic2 = {"Brasil":10,"Bolivia":10,"Japão":10}
serie2 = pd.Series(dic2)
serie1 + serie2

Bolivia     NaN
Brasil     20.0
EUA         NaN
Japão      20.0
dtype: float64

In [128]:
#unique
serie1 = pd.Series(['a','b','c','a','d','e','c','a','e','d'])
serie1.unique()

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [130]:
#Contando valores
serie1.value_counts().sort_index()/len(serie1)

a    0.3
b    0.1
c    0.2
d    0.2
e    0.2
dtype: float64

In [96]:
#isin - Para filtar valores
mask = serie1.isin(['b', 'c'])
mask

serie1[mask]

1    b
2    c
6    c
dtype: object

#### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [131]:
np.random.seed(42) #Para o rand ficar igual

lista = np.random.randn(5,3)
lista

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [133]:
pd.DataFrame(lista)

0         1         2
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918

In [134]:
index = ['a','b','c','d','e']
colunas = ['x','y','z']
dataFrame = pd.DataFrame(data = lista,index=index,columns=colunas)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [135]:
# acessando coluna 'x', retornando uma serie
dataFrame['x']

a    0.496714
b    1.523030
c    1.579213
d    0.542560
e    0.241962
Name: x, dtype: float64

In [136]:
# acessando colunas 'x' e 'y', retornando um dataframe
dataFrame[['x','y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153
c  1.579213  0.767435
d  0.542560 -0.463418
e  0.241962 -1.913280

In [137]:
#pegando ponto
dataFrame['x']['a']

0.4967141530112327

In [139]:
#Pegando linha
dataFrame.loc['a']

x    0.496714
y   -0.138264
z    0.647689
Name: a, dtype: float64

In [142]:
#Pegando linha por numero
dataFrame.iloc[0]

x    0.496714
y   -0.138264
z    0.647689
Name: a, dtype: float64

In [143]:
#pegando linha e colunuma
dataFrame.loc['a','x']

0.4967141530112327

In [145]:
dataFrame.loc[['a','c'],['x','y']]

x         y
a  0.496714 -0.138264
c  1.579213  0.767435

In [146]:
#nova coluna 
dataFrame['novo'] = dataFrame['x'] + dataFrame['y']
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [147]:
#remove mas não salva
dataFrame.drop('novo',axis=1)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [148]:
dataFrame

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [149]:
#remove e salva
dataFrame.drop('novo',axis=1,inplace=True)
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [151]:
#retirando colunas
dataFrame.drop('e')

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730

In [152]:
#Seleções através de condições
dataFrame>0

x      y      z
a  True  False   True
b  True  False  False
c  True   True  False
d  True  False  False
e  True  False  False

In [153]:
#utilizando condição como mascara para um novo dataFrame
dataFrame[dataFrame>0]

x         y         z
a  0.496714       NaN  0.647689
b  1.523030       NaN       NaN
c  1.579213  0.767435       NaN
d  0.542560       NaN       NaN
e  0.241962       NaN       NaN

In [154]:
#porem não salva
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [155]:
#retira a linha do y que tem um item menor que 0
dataFrame[dataFrame['y']>0]

x         y         z
c  1.579213  0.767435 -0.469474

In [156]:
#Mesma operação de cima porem so retorna o linha z
dataFrame[dataFrame['y']<0]['z']

a    0.647689
b   -0.234137
d   -0.465730
e   -1.724918
Name: z, dtype: float64

In [157]:
dataFrame

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [117]:
#resetando index
dataFrame.reset_index()

index         x         y         z
0     a  0.496714 -0.138264  0.647689
1     b  1.523030 -0.234153 -0.234137
2     c  1.579213  0.767435 -0.469474
3     d  0.542560 -0.463418 -0.465730
4     e  0.241962 -1.913280 -1.724918

In [118]:
#resetando index sem manter o index antigo
dataFrame.reset_index(drop=True)

x         y         z
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918

In [158]:
dataFrame['nomes'] = ['SP','RJ','BH','SSA','NV']

In [160]:
dataFrame

x         y         z nomes
a  0.496714 -0.138264  0.647689    SP
b  1.523030 -0.234153 -0.234137    RJ
c  1.579213  0.767435 -0.469474    BH
d  0.542560 -0.463418 -0.465730   SSA
e  0.241962 -1.913280 -1.724918    NV

In [161]:
#reordenando as colunas

dataFrame = dataFrame[['x', 'nomes', 'y', 'z']]
dataFrame

x nomes         y         z
a  0.496714    SP -0.138264  0.647689
b  1.523030    RJ -0.234153 -0.234137
c  1.579213    BH  0.767435 -0.469474
d  0.542560   SSA -0.463418 -0.465730
e  0.241962    NV -1.913280 -1.724918

In [162]:
#Alterando o nome das colunas
dataFrame.columns = ['x', 'estados', 'y', 'z']
dataFrame

x estados         y         z
a  0.496714      SP -0.138264  0.647689
b  1.523030      RJ -0.234153 -0.234137
c  1.579213      BH  0.767435 -0.469474
d  0.542560     SSA -0.463418 -0.465730
e  0.241962      NV -1.913280 -1.724918

In [163]:
#criando novo index
dataFrame.set_index('estados',inplace=True)

dataFrame

x         y         z
estados                              
SP       0.496714 -0.138264  0.647689
RJ       1.523030 -0.234153 -0.234137
BH       1.579213  0.767435 -0.469474
SSA      0.542560 -0.463418 -0.465730
NV       0.241962 -1.913280 -1.724918

In [171]:
dataFrame.loc['SP']

x    0.496714
y   -0.138264
z    0.647689
Name: SP, dtype: float64

**indices multiplos**

In [180]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [181]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [173]:
matriz = np.random.randn(6,2)
matriz

array([[-0.56228753, -1.01283112],
       [ 0.31424733, -0.90802408],
       [-1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 ],
       [-1.42474819, -0.54438272],
       [ 0.11092259, -1.15099358]])

In [174]:
df = pd.DataFrame(matriz,index=hier_index,columns=['A','B'])

df

A         B
G1 1 -0.562288 -1.012831
   2  0.314247 -0.908024
   3 -1.412304  1.465649
G2 1 -0.225776  0.067528
   2 -1.424748 -0.544383
   3  0.110923 -1.150994

In [179]:
df.loc['G1', 1]

A   -0.562288
B   -1.012831
Name: (G1, 1), dtype: float64

In [182]:
df.xs('G1')

A         B
1 -0.562288 -1.012831
2  0.314247 -0.908024
3 -1.412304  1.465649

##### Concats e merges

In [184]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['w','x','y'])
df2 = pd.DataFrame({'B':[1,2,3],'C':[4,5,6],'D':[7,8,9]},index=['x','y','z'])

In [185]:
df1

A  B  C
w  1  4  7
x  2  5  8
y  3  6  9

In [186]:
df2

B  C  D
x  1  4  7
y  2  5  8
z  3  6  9

In [187]:
pd.concat([df1,df2])

A  B  C    D
w  1.0  4  7  NaN
x  2.0  5  8  NaN
y  3.0  6  9  NaN
x  NaN  1  4  7.0
y  NaN  2  5  8.0
z  NaN  3  6  9.0

In [195]:
pd.concat([df1,df2],join='inner')

B  C
w  4  7
x  5  8
y  6  9
x  1  4
y  2  5
z  3  6

In [196]:
pd.concat([df1,df2],axis=1)

A    B    C    B    C    D
w  1.0  4.0  7.0  NaN  NaN  NaN
x  2.0  5.0  8.0  1.0  4.0  7.0
y  3.0  6.0  9.0  2.0  5.0  8.0
z  NaN  NaN  NaN  3.0  6.0  9.0

In [197]:
pd.concat([df1, df2], axis=1, join='inner')

A  B  C  B  C  D
x  2  5  8  1  4  7
y  3  6  9  2  5  8

In [201]:
df3 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor2":[3,4,5]})
df4 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor4":[3,4,5]})

df3 

Paises  valor1  Valor2
0     Br       1       3
1     Pt       2       4
2     Bo       3       5

In [202]:
df4

Paises  valor1  Valor4
0     Br       1       3
1     Pt       2       4
2     Bo       3       5

In [205]:
pd.merge(df3, df4, on='Paises')

Paises  valor1_x  Valor2  valor1_y  Valor4
0     Br         1       3         1       3
1     Pt         2       4         2       4
2     Bo         3       5         3       5

#### Importando dados

In [281]:
filename = '../datasets/imoveis_Rio_de_Janeiro.csv'
df_imoveis_rj = pd.read_csv(filename, sep=';', nrows=0)
df_imoveis_rj.columns

Index(['condominio', 'quartos', 'suites', 'vagas', 'area', 'bairro',
       'atualizacao', 'preco', 'distancia', 'pm2'],
      dtype='object')

In [218]:
df_imoveis_rj = pd.read_csv(filename, sep=';', nrows=10)
df_imoveis_rj.head()

condominio  quartos  suites  vagas  area  bairro  atualizacao   preco  \
0         350        1     0.0    1.0    21       1            1  340000   
1         800        1     0.0    1.0    64       1            0  770000   
2         674        1     0.0    1.0    61       1            1  600000   
3         700        1     1.0    1.0    70       1            0  700000   
4         440        1     0.0    1.0    44       1            2  515000   
5         917        1     1.0    1.0    60       1            2  630000   
6         850        1     1.0    1.0    65       1            2  740000   
7         350        1     1.0    1.0    43       1            0  570000   
8         440        1     1.0    1.0    26       1            0  430000   
9         510        1     1.0    1.0    42       1            3  500000   

   distancia       pm2  
0       99.0  16190.48  
1       99.0  12031.25  
2       99.0   9836.07  
3       99.0  10000.00  
4       99.0  11704.55  
5       99.0  10500.00  
6       99.0  11384.62  
7       99.0  13255.81  
8       99.0  16538.46  
9       99.0  11904.76

In [222]:
df_imoveis_rj = pd.read_csv(filename, sep=';', usecols=['condominio', 'quartos', 'suites', 'vagas', 'area', 'bairro'])
df_imoveis_rj.head()

condominio  quartos  suites  vagas  area  bairro
0         350        1     0.0    1.0    21       1
1         800        1     0.0    1.0    64       1
2         674        1     0.0    1.0    61       1
3         700        1     1.0    1.0    70       1
4         440        1     0.0    1.0    44       1

In [224]:
df_imoveis_rj = pd.read_csv(filename, sep=';')
df_imoveis_rj.head()

condominio  quartos  suites  vagas  area  bairro  atualizacao   preco  \
0         350        1     0.0    1.0    21       1            1  340000   
1         800        1     0.0    1.0    64       1            0  770000   
2         674        1     0.0    1.0    61       1            1  600000   
3         700        1     1.0    1.0    70       1            0  700000   
4         440        1     0.0    1.0    44       1            2  515000   

   distancia       pm2  
0       99.0  16190.48  
1       99.0  12031.25  
2       99.0   9836.07  
3       99.0  10000.00  
4       99.0  11704.55

##### Nan Values

In [234]:
#Drop nan
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [227]:
df.dropna(subset=['col2'])

col1   col2 col3
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [229]:
df

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [236]:
df['col1'] = df['col1'].fillna(0)
df

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz

In [242]:
np.mean(df['col2'])

555.0

In [241]:
df['col2'] = df['col2'].fillna(df['col2'].mean())
df

col1   col2 col3
0   1.0  555.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz